# ruff: noqa: D100
from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import VideosModel as OptionalModel
from .strict_models import VideosModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Ar,
        Bn,
        ContentDetails,
        De,
        DeDe,
        Default,
        En,
        EnGb,
        EsUs,
        FrFr,
        Hi,
        High,
        Id,
        It,
        Item,
        Iw,
        Ja,
        Ko,
        LiveStreamingDetails,
        Localizations,
        Localized,
        Location,
        Maxres,
        Medium,
        Ml,
        NlNl,
        Pa,
        PageInfo,
        PaidProductPlacementDetails,
        Pl,
        Player,
        PtBr,
        RecordingDetails,
        RegionRestriction,
        Ru,
        Snippet,
        Standard,
        Statistics,
        Status,
        Ta,
        Te,
        Thumbnails,
        TopicDetails,
        Uk,
        Und,
        VideosModel,
    )
else:
    from .optional_models import (
        Ar,
        Bn,
        ContentDetails,
        De,
        DeDe,
        Default,
        En,
        EnGb,
        EsUs,
        FrFr,
        Hi,
        High,
        Id,
        It,
        Item,
        Iw,
        Ja,
        Ko,
        LiveStreamingDetails,
        Localizations,
        Localized,
        Location,
        Maxres,
        Medium,
        Ml,
        NlNl,
        Pa,
        PageInfo,
        PaidProductPlacementDetails,
        Pl,
        Player,
        PtBr,
        RecordingDetails,
        RegionRestriction,
        Ru,
        Snippet,
        Standard,
        Statistics,
        Status,
        Ta,
        Te,
        Thumbnails,
        TopicDetails,
        Uk,
        Und,
        VideosModel,
    )

__all__ = [
    "Ar",
    "Bn",
    "ContentDetails",
    "De",
    "DeDe",
    "Default",
    "En",
    "EnGb",
    "EsUs",
    "FrFr",
    "Hi",
    "High",
    "Id",
    "It",
    "Item",
    "Iw",
    "Ja",
    "Ko",
    "LiveStreamingDetails",
    "Localizations",
    "Localized",
    "Location",
    "Maxres",
    "Medium",
    "Ml",
    "NlNl",
    "Pa",
    "PageInfo",
    "PaidProductPlacementDetails",
    "Pl",
    "Player",
    "PtBr",
    "RecordingDetails",
    "RegionRestriction",
    "Ru",
    "Snippet",
    "Standard",
    "Statistics",
    "Status",
    "Ta",
    "Te",
    "Thumbnails",
    "TopicDetails",
    "Uk",
    "Und",
    "VideosModel",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> VideosModel:
    """Read a downloaded file into VideosModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
