# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from datetime import timedelta

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Default(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Medium(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class High(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Standard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Maxres(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Thumbnails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    default: Default
    medium: Medium
    high: High
    standard: Standard | None = None
    maxres: Maxres | None = None


class Localized(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Snippet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    published_at: AwareDatetime = Field(..., alias="publishedAt")
    channel_id: str = Field(..., alias="channelId")
    title: str
    description: str
    thumbnails: Thumbnails
    channel_title: str = Field(..., alias="channelTitle")
    tags: list[str] | None = None
    category_id: str = Field(..., alias="categoryId")
    live_broadcast_content: str = Field(..., alias="liveBroadcastContent")
    default_language: str = Field(..., alias="defaultLanguage")
    localized: Localized
    default_audio_language: str = Field(..., alias="defaultAudioLanguage")


class ContentRating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    yt_rating: str | None = Field(None, alias="ytRating")


class RegionRestriction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    blocked: list[str]


class ContentDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    duration: timedelta
    dimension: timedelta
    definition: str
    caption: str
    licensed_content: bool = Field(..., alias="licensedContent")
    content_rating: ContentRating = Field(..., alias="contentRating")
    projection: str
    region_restriction: RegionRestriction | None = Field(
        None,
        alias="regionRestriction",
    )


class Status(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_status: str = Field(..., alias="uploadStatus")
    privacy_status: str = Field(..., alias="privacyStatus")
    license: str
    embeddable: bool
    public_stats_viewable: bool = Field(..., alias="publicStatsViewable")
    made_for_kids: bool = Field(..., alias="madeForKids")


class Statistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    view_count: str | None = Field(None, alias="viewCount")
    like_count: str | None = Field(None, alias="likeCount")
    favorite_count: str = Field(..., alias="favoriteCount")
    comment_count: str | None = Field(None, alias="commentCount")


class Player(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    embed_html: str = Field(..., alias="embedHtml")


class TopicDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    topic_categories: list[str] = Field(..., alias="topicCategories")


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    latitude: float
    longitude: float
    altitude: int


class RecordingDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location_description: str | None = Field(None, alias="locationDescription")
    location: Location | None = None
    recording_date: AwareDatetime | None = Field(None, alias="recordingDate")


class En(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class HiLatn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pa(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ml(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Hi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Uk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Id(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    description: str


class Bn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class It(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    title: str | None = None


class Ja(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class PtBr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FrFr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnGb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Iw(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    title: str | None = None


class Ta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class NlNl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    title: str | None = None


class DeDe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ru(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EsUs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Te(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ko(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhHans(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Nl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class MsSg(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class DeCh(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Mn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sw(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class No(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnUs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnAu(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Es(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Es419(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class NlBe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Cs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class DeAt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class De(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FaIr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fil(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fa(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnIe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class YueHk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class PtPt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FrBe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FrCa(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EsMx(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhSg(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhHk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Vi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Da(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ms(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhTw(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Th(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class BnIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhCn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FaAf(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Zh(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sv(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EsEs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class El(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class FrCh(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ga(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Kk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Tr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Hu(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Gu(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Yue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ro(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhHant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Mo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Tl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sq(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Brx(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnCa(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Localizations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: En | None = None
    hi_latn: HiLatn | None = Field(None, alias="hi-Latn")
    pl: Pl | None = None
    pa: Pa | None = None
    ml: Ml | None = None
    hi: Hi | None = None
    uk: Uk | None = None
    id: Id | None = None
    bn: Bn | None = None
    it: It | None = None
    ja: Ja | None = None
    pt_br: PtBr | None = Field(None, alias="pt-BR")
    fr_fr: FrFr | None = Field(None, alias="fr-FR")
    en_gb: EnGb | None = Field(None, alias="en-GB")
    iw: Iw | None = None
    ta: Ta | None = None
    nl_nl: NlNl | None = Field(None, alias="nl-NL")
    de_de: DeDe | None = Field(None, alias="de-DE")
    ru: Ru | None = None
    es_us: EsUs | None = Field(None, alias="es-US")
    ar: Ar | None = None
    te: Te | None = None
    ko: Ko | None = None
    sk: Sk | None = None
    zh_hans: ZhHans | None = Field(None, alias="zh-Hans")
    nl: Nl | None = None
    ms_sg: MsSg | None = Field(None, alias="ms-SG")
    de_ch: DeCh | None = Field(None, alias="de-CH")
    mn: Mn | None = None
    fr: Fr | None = None
    sw: Sw | None = None
    no: No | None = None
    en_us: EnUs | None = Field(None, alias="en-US")
    en_au: EnAu | None = Field(None, alias="en-AU")
    es: Es | None = None
    es_419: Es419 | None = Field(None, alias="es-419")
    fi: Fi | None = None
    nl_be: NlBe | None = Field(None, alias="nl-BE")
    cs: Cs | None = None
    de_at: DeAt | None = Field(None, alias="de-AT")
    de: De | None = None
    fa_ir: FaIr | None = Field(None, alias="fa-IR")
    fil: Fil | None = None
    fa: Fa | None = None
    en_ie: EnIe | None = Field(None, alias="en-IE")
    yue_hk: YueHk | None = Field(None, alias="yue-HK")
    pt_pt: PtPt | None = Field(None, alias="pt-PT")
    fr_be: FrBe | None = Field(None, alias="fr-BE")
    fr_ca: FrCa | None = Field(None, alias="fr-CA")
    es_mx: EsMx | None = Field(None, alias="es-MX")
    sr: Sr | None = None
    zh_sg: ZhSg | None = Field(None, alias="zh-SG")
    zh_hk: ZhHk | None = Field(None, alias="zh-HK")
    vi: Vi | None = None
    da: Da | None = None
    ms: Ms | None = None
    zh_tw: ZhTw | None = Field(None, alias="zh-TW")
    pt: Pt | None = None
    th: Th | None = None
    bn_in: BnIn | None = Field(None, alias="bn-IN")
    zh_cn: ZhCn | None = Field(None, alias="zh-CN")
    fa_af: FaAf | None = Field(None, alias="fa-AF")
    zh: Zh | None = None
    en_in: EnIn | None = Field(None, alias="en-IN")
    sv: Sv | None = None
    es_es: EsEs | None = Field(None, alias="es-ES")
    el: El | None = None
    fr_ch: FrCh | None = Field(None, alias="fr-CH")
    ga: Ga | None = None
    kk: Kk | None = None
    tr: Tr | None = None
    hu: Hu | None = None
    gu: Gu | None = None
    yue: Yue | None = None
    ro: Ro | None = None
    zh_hant: ZhHant | None = Field(None, alias="zh-Hant")
    mo: Mo | None = None
    tl: Tl | None = None
    sq: Sq | None = None
    brx: Brx | None = None
    en_ca: EnCa | None = Field(None, alias="en-CA")


class PaidProductPlacementDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    has_paid_product_placement: bool = Field(..., alias="hasPaidProductPlacement")


class LiveStreamingDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_live_chat_id: str | None = Field(None, alias="activeLiveChatId")
    actual_start_time: AwareDatetime | None = Field(None, alias="actualStartTime")
    actual_end_time: AwareDatetime | None = Field(None, alias="actualEndTime")
    scheduled_start_time: AwareDatetime | None = Field(
        None,
        alias="scheduledStartTime",
    )


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str
    etag: str
    id: str
    snippet: Snippet
    content_details: ContentDetails = Field(..., alias="contentDetails")
    status: Status
    statistics: Statistics
    player: Player
    topic_details: TopicDetails | None = Field(None, alias="topicDetails")
    recording_details: RecordingDetails = Field(..., alias="recordingDetails")
    localizations: Localizations
    paid_product_placement_details: PaidProductPlacementDetails = Field(
        ...,
        alias="paidProductPlacementDetails",
    )
    live_streaming_details: LiveStreamingDetails | None = Field(
        None,
        alias="liveStreamingDetails",
    )


class PageInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_results: int = Field(..., alias="totalResults")
    results_per_page: int = Field(..., alias="resultsPerPage")


class Video(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str
    etag: str
    items: list[Item]
    page_info: PageInfo = Field(..., alias="pageInfo")
