# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from datetime import timedelta

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Default(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Medium(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class High(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Standard(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Maxres(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    width: int
    height: int


class Thumbnails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    default: Default
    medium: Medium
    high: High
    standard: Standard | None = None
    maxres: Maxres | None = None


class Localized(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Snippet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    published_at: AwareDatetime = Field(..., alias="publishedAt")
    channel_id: str = Field(..., alias="channelId")
    title: str
    description: str
    thumbnails: Thumbnails
    channel_title: str = Field(..., alias="channelTitle")
    tags: list[str] | None = None
    category_id: str = Field(..., alias="categoryId")
    live_broadcast_content: str = Field(..., alias="liveBroadcastContent")
    default_language: str = Field(..., alias="defaultLanguage")
    localized: Localized
    default_audio_language: str = Field(..., alias="defaultAudioLanguage")


class ContentRating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    yt_rating: str | None = Field(None, alias="ytRating")


class RegionRestriction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    blocked: list[str]


class ContentDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    duration: timedelta
    dimension: str
    definition: str
    caption: str
    licensed_content: bool = Field(..., alias="licensedContent")
    content_rating: ContentRating = Field(..., alias="contentRating")
    projection: str
    region_restriction: RegionRestriction | None = Field(
        None,
        alias="regionRestriction",
    )


class Status(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_status: str = Field(..., alias="uploadStatus")
    privacy_status: str = Field(..., alias="privacyStatus")
    license: str
    embeddable: bool
    public_stats_viewable: bool = Field(..., alias="publicStatsViewable")
    made_for_kids: bool = Field(..., alias="madeForKids")


class Statistics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    view_count: str | None = Field(None, alias="viewCount")
    like_count: str | None = Field(None, alias="likeCount")
    favorite_count: str = Field(..., alias="favoriteCount")
    comment_count: str = Field(..., alias="commentCount")


class Player(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    embed_html: str = Field(..., alias="embedHtml")


class TopicDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    topic_categories: list[str] = Field(..., alias="topicCategories")


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    latitude: float
    longitude: float
    altitude: int


class RecordingDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location_description: str | None = Field(None, alias="locationDescription")
    location: Location | None = None
    recording_date: AwareDatetime | None = Field(None, alias="recordingDate")


class Ru(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class En(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class ZhTw(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ja(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ko(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EsUs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class It(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    description: str


class NlNl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    description: str


class EnGb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Id(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str | None = None
    description: str


class FrFr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class DeDe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pa(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ml(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Hi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Uk(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Bn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class PtBr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Iw(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    title: str | None = None


class Ta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class De(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class El(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Zh(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Ar(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Te(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Tr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Hu(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Pt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class EnUs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Fil(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Da(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Nl(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Sv(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Es(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class No(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Th(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Es419(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str


class Localizations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ru: Ru | None = None
    en: En | None = None
    zh_tw: ZhTw | None = Field(None, alias="zh-TW")
    ja: Ja | None = None
    ko: Ko | None = None
    es_us: EsUs | None = Field(None, alias="es-US")
    it: It | None = None
    nl_nl: NlNl | None = Field(None, alias="nl-NL")
    en_gb: EnGb | None = Field(None, alias="en-GB")
    id: Id | None = None
    fr_fr: FrFr | None = Field(None, alias="fr-FR")
    de_de: DeDe | None = Field(None, alias="de-DE")
    pl: Pl | None = None
    pa: Pa | None = None
    ml: Ml | None = None
    hi: Hi | None = None
    uk: Uk | None = None
    bn: Bn | None = None
    pt_br: PtBr | None = Field(None, alias="pt-BR")
    iw: Iw | None = None
    ta: Ta | None = None
    fr: Fr | None = None
    de: De | None = None
    el: El | None = None
    zh: Zh | None = None
    ar: Ar | None = None
    te: Te | None = None
    tr: Tr | None = None
    hu: Hu | None = None
    pt: Pt | None = None
    en_us: EnUs | None = Field(None, alias="en-US")
    fil: Fil | None = None
    da: Da | None = None
    nl: Nl | None = None
    sv: Sv | None = None
    es: Es | None = None
    no: No | None = None
    th: Th | None = None
    es_419: Es419 | None = Field(None, alias="es-419")


class PaidProductPlacementDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    has_paid_product_placement: bool = Field(..., alias="hasPaidProductPlacement")


class LiveStreamingDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    actual_start_time: AwareDatetime = Field(..., alias="actualStartTime")
    actual_end_time: AwareDatetime = Field(..., alias="actualEndTime")
    scheduled_start_time: AwareDatetime | None = Field(
        None,
        alias="scheduledStartTime",
    )


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str
    etag: str
    id: str
    snippet: Snippet
    content_details: ContentDetails = Field(..., alias="contentDetails")
    status: Status
    statistics: Statistics
    player: Player
    topic_details: TopicDetails | None = Field(None, alias="topicDetails")
    recording_details: RecordingDetails = Field(..., alias="recordingDetails")
    localizations: Localizations
    paid_product_placement_details: PaidProductPlacementDetails = Field(
        ...,
        alias="paidProductPlacementDetails",
    )
    live_streaming_details: LiveStreamingDetails | None = Field(
        None,
        alias="liveStreamingDetails",
    )


class PageInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_results: int = Field(..., alias="totalResults")
    results_per_page: int = Field(..., alias="resultsPerPage")


class Video(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str
    etag: str
    items: list[Item]
    page_info: PageInfo = Field(..., alias="pageInfo")
